trigger:
- main

pool:
  vmImage: 'ubuntu-24.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# - script: |
#     sudo apt-get update
#     sudo apt-get install -y openjdk-17-jdk
#   displayName: 'Install OpenJDK 17'

# - script: |
#     JAVA_17_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    
#     # Set JAVA_HOME to point to Java 17
#     echo "##vso[task.setvariable variable=JAVA_HOME]$JAVA_17_HOME"
    
#     # Prepend Java 17 to PATH to ensure it's the default in this pipeline
#     echo "##vso[task.setvariable variable=PATH]$JAVA_17_HOME/bin:$(PATH)"
#   displayName: 'Set JAVA_HOME to Java 17'

- script: |
    sudo add-apt-repository ppa:dotnet/backports    
    sudo apt-get update && \
    sudo apt-get install -y dotnet-sdk-9.0
  displayName: 'Install .NET 9.0 SDK'

#- pwsh: |
#      dotnet ./scanner/SonarScanner.MSBuild.dll begin /o:"alexmeseldzija" /k:"alexmeseldzija_alex-test" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.token="21d941b2f90bc284309dfed9bc1fa611bd39feed" /d:sonar.verbose=true
#  workingDirectory: '$(Build.SourcesDirectory)'
#  displayName: 'run scanner prep'
- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'Alex SonarCloud Token'
    organization: 'alexmeseldzija'
    scannerMode: 'MSBuild'
    projectKey: 'alexmeseldzija_alex-test'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.exclusions=**/*.bin
      sonar.scanner.scanAll=true
      sonar.verbose=true
      sonar.exclusions="**/*.yaml"
      sonar.cpd.cs.minimumTokens=2
      sonar.cpd.cs.minimumLines=2

#- pwsh: |
#      chmod -R +x ./scanner/sonar-scanner-5.0.1.3006/bin/*
#  workingDirectory: '$(Build.SourcesDirectory)'
#  displayName: 'chmod perms'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '**/*.sln'

#- pwsh: |
#    dotnet ./scanner/SonarScanner.MSBuild.dll end /d:sonar.token="21d941b2f90bc284309dfed9bc1fa611bd39feed"  
#  workingDirectory: '$(Build.SourcesDirectory)'
#  displayName: 'run scanner endstep'

- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'