trigger:
- main

pool:
  vmImage: 'macOS-14'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Restore solution'
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'

- script: |
    brew update
    brew install openjdk-17-jdk
    sudo ln -sfn $(brew --prefix openjdk@17)/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-17.jdk
  displayName: 'Install OpenJDK 17'

#- script: |
#    JAVA_17_HOME=$(/usr/libexec/java_home -v 17)
#    
#    # Set JAVA_HOME for subsequent steps
#    echo "##vso[task.setvariable variable=JAVA_HOME]$JAVA_17_HOME"
#    
#    # Add JAVA_HOME to the PATH to ensure Java 17 is used
#    echo "##vso[task.setvariable variable=PATH]$JAVA_17_HOME/bin:$(PATH)"
#  displayName: 'Set JAVA_HOME to Java 17'


- script: |
    echo "JAVA_HOME: $JAVA_HOME"
    echo "PATH: $PATH"
    java -version
  displayName: 'Verify Java Installation'

- pwsh: |
      dotnet ./scanner/SonarScanner.MSBuild.dll begin /o:"alexmeseldzija" /k:"alexmeseldzija_alex-test" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.token="21d941b2f90bc284309dfed9bc1fa611bd39feed" /d:sonar.verbose=true /d:sonar.scanner.scanAll=true /d:sonar.projectBaseDir="$(Build.SourcesDirectory)/Playground"
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'run scanner prep'


- pwsh: |
      chmod -R +x ./scanner/sonar-scanner-5.0.1.3006/bin/*
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'chmod perms'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Execute Unit tests'
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--collect "Code Coverage"'

- pwsh: |
    dotnet ./scanner/SonarScanner.MSBuild.dll end /d:sonar.token="21d941b2f90bc284309dfed9bc1fa611bd39feed"  
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'run scanner endstep'