trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore solution'
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'

- task: PowerShell@2
  displayName: "Powershell prepare scanner"
  inputs:
    targetType: 'inline'
    script: |
      .\scanner\SonarScanner.MSBuild.exe begin 
      /o:"alexmeseldzija" 
      /k:"alexmeseldzija_alex-test" 
      /d:sonar.host.url="https://sonarcloud.io" 
      /d:sonar.token="21d941b2f90bc284309dfed9bc1fa611bd39feed" 
      /d:sonar.verbose=true
      

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Execute Unit tests'
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--collect "Code Coverage"'

- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@1
  displayName: 'Publish results on build summary'
  inputs:
    pollingTimeoutSec: '300'